version: "4"
volumes:
  db_volume:
  log_volume:
networks:
  my_app:
    driver: bridge
services:
  postgres:
    container_name: throttler_postgres
    image: postgres:12.13-alpine
    environment:
      POSTGRES_DB: "throttler"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_app
  throttler-go:
    build: ./
    container_name: throttler_app
    image: throttler-go
    environment:
      LOG_LEVEL: "debug"
      PG_URL: "postgres://user:pass@postgres:5432/throttler?sslmode=disable"
      ENABLE_REDIS: false
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - log_volume:/root/logs
    networks:
      - my_app
  redis:
    image: redis:6.0-alpine
    container_name: throttler_redis
    networks:
      - my_app
    ports:
      - "6379:6379"