version: "4"
volumes:
  db_volume:
services:
  postgres:
    container_name: throttler_postgres
    image: postgres:12.13-alpine
    environment:
      POSTGRES_DB: "throttler"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
